markdown: kramdown
permalink: pretty
exclude: ["node_modules", "gulpfile.js", "package.json"]
collections:
  projects:
    output: true

prose:
  rooturl: '_projects'
  siteurl: "https://lincolnsavage.github.io/"
